version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    image: v1tam1np1/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  # frontend:
  #   env_file: ../.env
  #   # image: v1tam1np1/kittygram_frontend
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   command: cp -r /app/result_build/. /frontend_static/
  #   volumes:
  #     - static:/frontend_static
  nginx:
    # image: nginx:1.19.3
    image: v1tam1np1/foodgram_gateway
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
  backend:
    image: v1tam1np1/foodgram_backend
    depends_on:
      - db
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/app/collected_static/
      - media:/app/media
