# Generated by Django 3.2 on 2023-07-12 07:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_auto_20230711_1041"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ("ingredient",),
                "verbose_name": "Ингредиент и рецепт",
                "verbose_name_plural": "Ингредиенты и рецепты",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
    ]
