# Generated by Django 3.2 on 2023-07-12 08:32

from django.db import migrations, models
import recipe.validators


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_auto_20230712_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[recipe.validators.hex_color_validator],
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Тэг"
            ),
        ),
    ]
