# Generated by Django 3.2 on 2023-07-16 08:10

from django.db import migrations, models
import django.utils.timezone
import recipe.validators


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_auto_20230713_1255"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[recipe.validators.hex_color_validator],
            ),
        ),
    ]
