# Generated by Django 3.2 on 2023-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0008_auto_20230724_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Рецепт"),
        ),
    ]
