# Generated by Django 3.2 on 2023-07-17 08:00

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20230711_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    users.validators.validate_username,
                    users.validators.validate_username_bad_sign,
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
