# Generated by Django 3.2 on 2023-07-24 07:17

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    users.validators.validate_username,
                    users.validators.validate_username_bad_sign,
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
