# Generated by Django 3.2 on 2023-07-24 07:39

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_auto_20230724_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Введите правильное имя пользователя."
                },
                max_length=150,
                unique=True,
                validators=[
                    users.validators.validate_username,
                    users.validators.validate_username_bad_sign,
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
