# Generated by Django 3.2 on 2023-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20230724_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email"
            ),
        ),
    ]
